sudo: required
services: 
  - docker
before_install:
  - docker build -t siddharthsal99/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true siddharthsal99/react-test npm test

after_success:
  - docker build -t siddharthsal99/multi-client ./client
  - docker build -t siddharthsal99/multi-server ./server
  - docker build -t siddharthsal99/multi-nginx ./nginx
  - docker build -t siddharthsal99/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push siddharthsal99/multi-client
  - docker push siddharthsal99/multi-server
  - docker push siddharthsal99/multi-nginx
  - docker push siddharthsal99/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-162351837088'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY