sudo: required
services: 
  - docker
before_install:
  - docker build -t siddharthsal99/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true siddharthsal99/react-test npm test -- --coverage

after_success:
  - docker build -t siddharthsal99/multi-client ./client
  - docker build -t siddharthsal99/multi-server ./server
  - docker build -t siddharthsal99/multi-nginx ./nginx
  - docker build -t siddharthsal99/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push siddharthsal99/multi-client
  - docker push siddharthsal99/multi-server
  - docker push siddharthsal99/multi-nginx
  - docker push siddharthsal99/multi-worker